### ISSUE TITLE
QA 0.2.3 pre-release Bugs and Issues #3

### ISSUE THREAD

**Issue by hmakandi** [OpenSRP/opensrp-client-giz-malawi#162]
- [x] Malawi team have not yet decided whether to make Back entry of data possible or not. Thus for the expired vaccines, allow them to be shown as overdue, to allow data entry just like below. When they confirm that they want them expired, then we shall change it back. Allow this change to be configurable.
![Screenshot_1576491556](https://user-images.githubusercontent.com/18394882/70898994-d265c900-2006-11ea-886d-a5d20108151b.png)

- [x] App crashes on record growth. Steps: Register a new child born today, click on the child's record, then go to record growth
![Screenshot_1576493400](https://user-images.githubusercontent.com/18394882/70901104-2d99ba80-200b-11ea-8522-07789da1a2e5.png)

- [x] Steps:Click + to register a child, fill in all the required details PAB at birth field is no longer in the child's registration form. Please return it as per issues #140 where an additional question on TTV was requested to educate a calculation for the PAB.

- [x] Add a new field for Child Register Number
"Child register has a 3 digit child registration number which is also recorded on the health passport. It was noted that the facility has not yet implemented the Child Birth Registration Number. Until Birth Registration is fully functional Nationwide or Unless the App is linked to the NRB System the request is we will have to allow the 3 digit number to be registered in system." #140 

- [x] Adverse effect allows selection of earlier date than the date of the immunisation #113 

- [ ] Increase mother match lookup to 60seconds #140 

- [ ]

**Comment by hmakandi** [comment]
- Confirmed growth not crashing, back data entry and the new form fields

- Confirmed Adverse effect starts at the date of the immunization

- PAB has relevance of only show when <=2 years

- Mother match lookup moved to #164
