### ISSUE TITLE
Release 0.1.3. UAT bugs 

### ISSUE THREAD

**Issue by hmakandi** [OpenSRP/opensrp-client-giz-malawi#48]
- [x] On edit of the registration data within the Child profile, and clicking save does not refresh the UI on the Child's profile. The user has to go back to the child's register page, and click on the child to see the newly changed details.

- [x] On save of edit registration data, the registration history tab should refresh to reflect the new data

- [x] Return error if the server url settings is blank or has incorrect url [#308](https://github.com/OpenSRP/opensrp-client-core/issues/308)

- [x] Disable QR code and edit of MER ID[ issue 50](https://github.com/OpenSRP/opensrp-client-giz-malawi/issues/50)

- [x] Select Service Location via Location hierarchy [issue 44](https://github.com/OpenSRP/opensrp-client-giz-malawi/issues/44)

- [x] - [ ] Record growth button on the register page [issue 51](https://github.com/OpenSRP/opensrp-client-giz-malawi/issues/51)

- [x] Recurring Services [issue 52](https://github.com/OpenSRP/opensrp-client-giz-malawi/issues/52)

- [x] Automatic Sync [issue 34](https://github.com/OpenSRP/opensrp-client-giz-malawi/issues/34)

- [x] Relevance on forms, mandatory fields, make ID alphanumeric [issue 53](https://github.com/OpenSRP/opensrp-client-giz-malawi/issues/53)

- [x] Sync refresh the register[ issue 55](https://github.com/OpenSRP/opensrp-client-giz-malawi/issues/55)

**Comment by hmakandi** [comment]
Issue on services locations to be tracked via https://github.com/OpenSRP/opensrp-client-giz-malawi/issues/46
