### ISSUE TITLE
ANC Integration: Navigation and design harmornization

### ISSUE THREAD

**Issue by hmakandi** [OpenSRP/opensrp-client-giz-malawi#84]
- [x] When on the ANC register , there is no way provided to go back to the navigation pane. Replace the originally designed Scan QR code to have the Hamburger menu for the navigation pane. Ensure swipe right also shows the navigation pane
![Screenshot_1567397170](https://user-images.githubusercontent.com/18394882/64089757-61005400-cd50-11e9-8470-5cdb033a86d3.png)

- [x] Update as per new design in [issue 47](https://github.com/OpenSRP/opensrp-client-giz-malawi/issues/47)

- [x] ANC counter as per [issue 46](https://github.com/OpenSRP/opensrp-client-giz-malawi/issues/46) and [issue 41](https://github.com/OpenSRP/opensrp-client-giz-malawi/issues/41)

- [x] Remove the bottom navigation and move items as per the new design in [issue 46](https://github.com/OpenSRP/opensrp-client-giz-malawi/issues/46)

- [x] Refresh UI on sync as per[ issue 55
](https://github.com/OpenSRP/opensrp-client-giz-malawi/issues/55)

- [x] The settings should link to the ANC "Me" page from ANC

- [x] All clients counter to reflect all available clients within the app. [Issue 45](https://github.com/OpenSRP/opensrp-client-giz-malawi/issues/45)

- [x] Note that for this project, the Library tab is not required

**Comment by hmakandi** [comment]
Confirmed
